# Server configuration
server.port=8080

# Logging configuration
logging.level.com.bytecoder.kaleidopipelines=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# Spring configuration
spring.main.banner-mode=off
spring.application.name=kaleido-pipelines
